# Generated by Django 4.2.6 on 2023-11-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp2', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatares'),
        ),
    ]
